### PR TITLE
fix: handles pfx certs in k8s secrets sync

### LINKED ISSUE #1057: SPC with synced K8S Secret populating the secret with an "empty" cert
**What steps did you take and what happened:**
We have a fairly standard app consisting of a Deployment, Service, SPC w/ synced Secrets, and Ingress. The SPC is mounted on the deployment pods and is syncing secrets that the ingress references as TLS certs. However, the synced secrets' data sections have only empty values:
```yaml
data:
  tls.crt: ""
  tls.key: <base64-encoded "---BEGIN PRIVATE KEY---\n---END PRIVATE KEY---". Just those lines, no content.>
```

**What did you expect to happen:**
The referenced certificate to be synced successfully

**Anything else you would like to add:**
So as described above, we have an app with a fairly standard setup of ingresses, and when deploying it, we're hitting a rather strange scenario where it's syncing an "empty" secret. Specs included below, as they're rather large - in essence, an SPC has a _somewhat_ large (about 8) set of synced objects it's using for creating a set of ingress secrets. the SPC is mounted on the pod and works fine - the pod starts up successfully - but the secrets that are synced are invalid.

In particular, the equivalent of ` notebook-instance-proxy-managed-ingress-ssl-synced` in our specs is empty, with the contents I pasted above:
```yaml
data:
  tls.crt: ""
  tls.key: <base64-encoded "---BEGIN PRIVATE KEY---\n---END PRIVATE KEY---">
```

I've checked through a wide variety of logs from both csi and azure components - there were no error logs, and all logs mentioning the pod name or SPC indicated nothing went wrong or differently than any of our other deployments that use CSI Driver.

It doesn't appear to be like a one off transient issue, as deployments of that same build to a different namespace (for PR gates) also have the same issue. deleting and redeploying the app to recreate the secrets has resulted in the same issue as well. We're kind of at a loss for what might be going on.

The only thing that's stood out to me so far is that the SPC in question has a relatively large number of separately-synced objects.

One other notable fact might be that we've migrated from self-hosted to AKS-hosted CSI driver, in case there might be some strangeness with that handover.

Spec note - these approximate the shape of what we're doing with some stuff omitted for brevity or security. I can privately send over a more complete set of files if needed.
```yaml
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # [... Truncated ...]
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: notebook-instance-proxy
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notebook-instance-proxy
        app-web: notebook-instance-proxy
      namespace: vienna-master
    spec:
      containers:
        # [ ... Truncated ... ]
        volumeMounts:
        - mountPath: /app/secrets/
          name: secrets-volume
          readOnly: true
      # [ ... Truncated ... ]
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          nodePublishSecretRef:
            name: notebook-instance-proxy-kv-creds
          readOnly: true
          volumeAttributes:
            secretProviderClass: notebook-instance-proxy-secretprovider
        name: secrets-volume

---
# SPC
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notebook-instance-proxy-secretprovider
  namespace: vienna-master
spec:
  parameters:
    cloudEnvFileName: /
    cloudName: AZUREPUBLICCLOUD
    keyvaultName: <ommitted>
    objects: |
      array:
        - |
          objectName: "cert-1"
          objectAlias: "cert-1"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-2"
          objectAlias: "cert-2"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-3"
          objectAlias: "cert-3"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-4"
          objectAlias: "cert-4"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-5"
          objectAlias: "cert-5"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-6"
          objectAlias: "cert-6"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-7"
          objectAlias: "cert-7"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-8"
          objectAlias: "cert-8"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "secret-1"
          objectAlias: "secret-1"
          objectType: secret
        - |
          objectName: "secret-2"
          objectAlias: "secret-2"
          objectType: secret
        - |
          objectName: "secret-3"
          objectAlias: "secret-3"
          objectType: secret
        - |
          objectName: "secret-4"
          objectAlias: "secret-4"
          objectType: secret
        - |
          objectName: "secret-5"
          objectAlias: "secret-5"
          objectType: secret
        - |
          objectName: "secret-6"
          objectAlias: "secret-6"
          objectType: secret
    tenantId: <ommitted>
  provider: azure
  secretObjects:
  - data:
    - key: tls.crt
      objectName: cert-1
    - key: tls.key
      objectName: cert-1
    secretName: notebook-instance-proxy-managed-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-2
    - key: tls.key
      objectName: cert-2
    secretName: notebook-instance-proxy-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-3
    - key: tls.key
      objectName: cert-3
    secretName: notebook-instance-proxy-modern-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-4
    - key: tls.key
      objectName: cert-4
    secretName: notebook-instance-proxy-managed-ms-ingress-internal-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-5
    - key: tls.key
      objectName: cert-5
    secretName: notebook-instance-proxy-nodes-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-6
    - key: tls.key
      objectName: cert-6
    secretName: notebook-instance-proxy-certapi-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: secret-1
      objectName: secret-1
    - key: secret-2
      objectName: secret-2
    - key: secret-3
      objectName: secret-3
    - key: secret-4
      objectName: secret-4
    - key: secret-5
      objectName: secret-5
    - key: secret-6
      objectName: secret-6
    secretName: notebook-instance-proxy-synced
    type: Opaque

---

# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # [... ommitted ...]
  generation: 48
  name: notebook-instance-proxy-ingress
  namespace: vienna-master
spec:
  rules:
  - host: auth.master.instances.azureml-test.ms
    http:
      paths:
      - backend:
          service:
            name: notebook-instance-proxy
            port:
              number: 443
        path: /
        pathType: Prefix
  - host: '*.master.instances.azureml-test.net'
    http:
      paths:
      - backend:
          service:
            name: notebook-instance-proxy
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - '*.master.instances.azureml-test.net'
    secretName: notebook-instance-proxy-managed-ingress-ssl-synced
  - hosts:
    - auth.master.instances.azureml-test.ms
    - '*.master.instances.azureml-test.ms'
    secretName: notebook-instance-proxy-modern-ingress-ssl-synced
```

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): AKS-managed
- Kubernetes version: (use `kubectl version`): 1.23

### PR DESCRIPTION
**Pull request by nilekhc**
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #1057

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

### CODE REVIEW

**Review by jroggeman — APPROVED** [review]

File: pkg/util/secretutil/secret.go [hunk 1]
```diff
@@ -28,6 +28,7 @@ import (
 	"sort"
 	"strings"
 
+	"golang.org/x/crypto/pkcs12"
```
Comment (aramase) [inline pkg/util/secretutil/secret.go:31]: Move this after line 34 and group with `corev1 "k8s.io/api/core/v1"` as they're external packages

File: pkg/util/secretutil/secret.go [hunk 2]
```diff
@@ -84,6 +102,19 @@ func getPrivateKey(data []byte) ([]byte, error) {
 		data = rest
 	}
 
+	// if both der and pemBlock are nil, then it might be a pfx cert
```
Comment (aramase) [inline pkg/util/secretutil/secret.go:105]:
```suggestion
	// if both der and pemBlock are nil, then it might be in the pfx format
```

File: pkg/util/secretutil/secret.go [hunk 3]
```diff
@@ -84,6 +102,19 @@ func getPrivateKey(data []byte) ([]byte, error) {
...
+	if der == nil && pemBlock == nil {
```
Comment (aramase) [inline pkg/util/secretutil/secret.go:106]: The `for` loop only breaks when `pemBlock == nil` is true. Is the `pemBlock == nil` check here redundant? If yes, can we remove it?

File: pkg/util/secretutil/secret.go [hunk 4]
```diff
@@ -84,6 +102,19 @@ func getPrivateKey(data []byte) ([]byte, error) {
...
+		key, _, err := pkcs12.Decode(data, "")
```
Comment (aramase) [inline pkg/util/secretutil/secret.go:107]: If we use `der` instead of new variable key, couldn't we rely on existing key parsing logic to marshal based on the key type (same as today)?

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/b2631980e2790b102dfb78afa4c90fa9c3c83fff/pkg/util/secretutil/secret.go#L87-L115

File: pkg/util/secretutil/secret.go [hunk 5]
```diff
@@ -84,6 +102,19 @@ func getPrivateKey(data []byte) ([]byte, error) {
...
+		if err != nil {
+			return nil, fmt.Errorf("failed to decode pkcs12 data, err: %w", err)
+		}
+
+		derKey, err = x509.MarshalPKCS8PrivateKey(key.(*rsa.PrivateKey))
+		if err != nil {
+			return nil, fmt.Errorf("failed to marshal private key, err: %w", err)
+		}
```
Comment (aramase) [inline pkg/util/secretutil/secret.go:115]: same comment as above (instead of `MarshalPKCS8PrivateKey`, could we reuse the existing key parse logic?)

File: pkg/util/secretutil/secret_test.go [hunk 6]
```diff
@@ -168,6 +169,53 @@ func TestGetCert(t *testing.T) {
 	}
 }
 
+func TestPfxGetCert(t *testing.T) {
```
Comment (aramase) [inline pkg/util/secretutil/secret_test.go:172]: Instead of a new test, I would recommend adding a new table test in [`TestGetCert`](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/pkg/util/secretutil/secret_test.go#L133)

File: pkg/util/secretutil/secret_test.go [hunk 7]
```diff
@@ -597,6 +645,63 @@ g+Ia2YI15BzapW0agqSSTlfGMoQHaPRh1+XYtkOd/xb4xc8d+gc0
 	}
 }
 
+func TestPfxGetPrivateKey(t *testing.T) {
```
Comment (aramase) [inline pkg/util/secretutil/secret_test.go:648]: Instead of a new test, I would recommend adding a new table test in [`TestGetPrivateKey `](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/pkg/util/secretutil/secret_test.go#L398)

**Review by aramase — CHANGES_REQUESTED** [review]

File: pkg/util/secretutil/secret.go (hunk 4 above)
Comment (nilekhc) [reply pkg/util/secretutil/secret.go:107]: With `pkcs12.Decode` we directly get the private key and don't have to parse it. So I am directly marshaling it and assigning it to `derKey`. Let me know if I am missing something here.

File: pkg/util/secretutil/secret.go (hunk 5 above)
Comment (nilekhc) [reply pkg/util/secretutil/secret.go:115]: Same as above. IMO we don't need to parse it.

File: pkg/util/secretutil/secret_test.go (hunk 7 above)
Comment (nilekhc) [reply pkg/util/secretutil/secret_test.go:648]: I thought about it. But for PFX I am having an input in base64 encoded format and need to decode it before we pass it to the function. It's not needed for existing tests and hence created a new test to keep it clean.

File: pkg/util/secretutil/secret_test.go (hunk 6 above)
Comment (nilekhc) [reply pkg/util/secretutil/secret_test.go:172]: Same as other test explanations.

File: pkg/util/secretutil/secret.go (hunk 4 above)
Comment (aramase) [reply pkg/util/secretutil/secret.go:107]: We get the private key with `pem.Decode` too. The rest of the code here is to parse and determine if there is an error, if not we marshal it with the appropriate type (RSA/EC). By always using `MarshalPKCS1PrivateKey` here, we're assuming it's in PKCS #1 and not PKCS #8, which isn't valid. The parse code handles those scenarios and as part of the PEM block returned, it set the correct key type (`EC` or `RSA`

File: pkg/util/secretutil/secret_test.go (hunk 7 above)
Comment (aramase) [reply pkg/util/secretutil/secret_test.go:648]: You can make actual a function field `func() []byte` and use that as input for `getPrivateKey`. We don't have to worry about the base64 decode error because we pass valid inputs but if we want we can still assert that in the function. Only reason for having all these tests in one is to ensure we always assert the same things for a function unit test.

**Review by aramase — APPROVED** [review]
/lgtm
/approve
