### PR TITLE
fix: use namespace for spc lookup + unit tests

### LINKED ISSUE #263: namespace lookup for SecretProviderClass not enforced in NodePublishVolume
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`podNamespace` is set after fetching `SecretProviderClass` which means the namespace match isn't strictly enforced

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/d59cc202c99980546a68d354206cbb792f80ef19/pkg/secrets-store/nodeserver.go#L151

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/d59cc202c99980546a68d354206cbb792f80ef19/pkg/secrets-store/nodeserver.go#L133

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by aramase**
**What this PR does / why we need it**:
- Sets the `podNamespace` env var for strict namespace enforcement
- Refactors `NodePublishVolume` to add more unit test for the `NodePublish` code path
- Updates logs to include pod name and pod namespace for debugging
- Adds unit tests 

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #263 

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/secrets-store/nodeserver_test.go [hunk 1]
```diff
@@ -84,14 +96,154 @@ func TestNodePublishVolume(t *testing.T) {
...
+					Spec: v1alpha1.SecretProviderClassSpec{
+						Provider:   "provider1",
+						Parameters: map[string]string{"parameter1": "value1"},
+					},
+				},
+			},
+			expectedErr: true,
+		},
+		{
+			name: "failed to invoke provider, unmounted to force retry",
```
Comment (ritazh) [inline pkg/secrets-store/nodeserver_test.go:179]: where do we test retry?

File: cmd/secrets-store-csi-driver/main.go [hunk 2]
```diff
@@ -96,5 +98,13 @@ func main() {
 
 func handle() {
 	driver := secretsstore.GetDriver()
-	driver.Run(*driverName, *nodeID, *endpoint, *providerVolumePath, *minProviderVersion)
+	cfg, err := config.GetConfig()
```
Comment (ritazh) [inline cmd/secrets-store-csi-driver/main.go:101]: I recall we had to call `getClient()` to get the latest client to prevent from reading from cache. Is this no longer a concern?

File: test/bats/azure.bats [hunk 3]
```diff
@@ -125,13 +126,70 @@ setup() {
   [[ "${result//$'\r'}" -eq "${SECRET_VALUE}" ]]
 
   result=$(kubectl get secret foosecret -o json | jq '.metadata.ownerReferences | length')
-  [[ "$result" -eq "2" ]]
+  [[ "$result" == "2" ]]
```
Comment (ritazh) [inline test/bats/azure.bats:129]: i think `==` fails for some systems. can we make sure we consistently use `-eq` in case people need to run this locally?

File: test/bats/azure.bats [hunk 4]
```diff
@@ -125,13 +126,70 @@ setup() {
...
+
+  run kubectl create secret generic secrets-store-creds --from-literal clientid=${AZURE_CLIENT_ID} --from-literal clientsecret=${AZURE_CLIENT_SECRET} -n test-ns
+  assert_success
+
+  envsubst < $BATS_TESTS_DIR/azure_v1alpha1_secretproviderclass_ns.yaml | kubectl apply -f -
+
+  cmd="kubectl wait --for condition=established --timeout=60s crd/secretproviderclasses.secrets-store.csi.x-k8s.io"
+  wait_for_process $WAIT_TIME $SLEEP_TIME "$cmd"
+
+  cmd="kubectl get secretproviderclasses.secrets-store.csi.x-k8s.io/azure-sync -o yaml | grep azure"
```
Comment (ritazh) [inline test/bats/azure.bats:156]: why are we checking this in default ns? seems it's deleted on line 136

File: test/bats/azure.bats [hunk 5]
```diff
@@ -125,13 +126,70 @@ setup() {
...
+  wait_for_process $WAIT_TIME $SLEEP_TIME "$cmd"
+
+  cmd="kubectl get secretproviderclasses.secrets-store.csi.x-k8s.io/azure-sync -n test-ns -o yaml | grep azure"
```
Comment (ritazh) [inline test/bats/azure.bats:159]: is there also a negative test for referring to a spc in a different ns?

File: test/bats/azure.bats (hunk 4 above)
Comment (aramase) [reply test/bats/azure.bats:156]: `azure_v1alpha1_secretproviderclass_ns.yaml` creates 2 spc with the same name, one in `default` namespace and other in `test-ns`. This test ensures the spc in the same namespace as pod is matched and not the one in default namespace. The default namespace spc has an invalid provider - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/264/files#diff-b09039a0f14308e43877bb2112de35f1R6 which is a good sign to ensure the correct SPC is always matched

Comment (ritazh) [reply test/bats/azure.bats:156]: ah ok. i missed that.

File: cmd/secrets-store-csi-driver/main.go (hunk 2 above)
Comment (aramase) [reply cmd/secrets-store-csi-driver/main.go:101]: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L42-L52

```
// New returns a new Client using the provided config and Options.
// The returned client reads *and* writes directly from the server
// (it doesn't use object caches).  It understands how to work with
// normal types (both custom resources and aggregated/built-in resources),
// as well as unstructured types.
```

**Comment by aramase** [comment]
@ritazh Updated the PR, PTAL!

File: pkg/secrets-store/nodeserver_test.go (hunk 1 above)
Comment (aramase) [reply pkg/secrets-store/nodeserver_test.go:189]: Added another loop just to test retry for all the failed calls

File: test/bats/azure.bats (hunk 5 above)
Comment (aramase) [reply test/bats/azure.bats:159]: Added a negative test case that deploy pods in `negative-test-ns`. The mount will fail with 

```
  Warning  FailedMount  3s (x8 over 67s)  kubelet, aks-nodepool1-36438484-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to get secretproviderclass negative-test-ns/azure-sync, error: secretproviderclasses.secrets-store.csi.x-k8s.io "azure-sync" not found
```

File: cmd/secrets-store-csi-driver/main.go (hunk 2 above)
Comment (ritazh) [reply cmd/secrets-store-csi-driver/main.go:101]: I was thinking about this one https://github.com/kubernetes-sigs/controller-runtime/issues/403
But I dont think we have multiple controllers updating the same objects now.

Comment (aramase) [reply cmd/secrets-store-csi-driver/main.go:101]: Right, we don't have any update operations on `spc`. There is only `GET` for `spc` and `CREATE` for `spcpodstatus`

File: test/bats/vault.bats [hunk 6]
```diff
@@ -188,7 +189,79 @@ EOF
...
+  envsubst < $BATS_TESTS_DIR/nginx-deployment-synck8s.yaml | kubectl apply -n test-ns -f -
+
+  cmd="kubectl wait --for=condition=Ready --timeout=60s pod -l app=nginx -n test-ns"
+  wait_for_process $WAIT_TIME $SLEEP_TIME "$cmd"
+}
+
+@test "Test Namespaced scope SecretProviderClass - Sync with K8s secrets - read secret from pod, read K8s secret, read env var, check secret ownerReferences" {
+  POD=$(kubectl get pod -l app=nginx -n test-ns -o jsonpath="{.items[0].metadata.name}")
+  result=$(kubectl exec -n test-ns -it $POD -- cat /mnt/secrets-store/foo)
+  [[ "$result" == "hello" ]]
```
Comment (ritazh) [inline test/bats/vault.bats:227]: can you pls update all these `==` to `-eq`

Comment (aramase) [reply test/bats/vault.bats:227]: I think we should use `==` for string comparisons. Using `-eq` returns 0 even when the strings don't match. 

```
#!/usr/bin/env bats

export result="hel"

@test "testing with eq" {
    [[ "$result" -eq "hello" ]]
}

@test "testing with other" {
    [[ "$result" == *"hello"* ]]
}

➜ bats test.bats -t
1..2
ok 1 testing with eq
not ok 2 testing with other
# (in test file /Users/anishramasekar/Desktop/test.bats, line 9)
#   `@test "testing with other" {' failed
```

File: test/bats/vault.bats [hunk 7]
```diff
@@ -188,7 +189,79 @@ EOF
 @test "Sync with K8s secrets - delete deployment, check secret is deleted" {
   run kubectl delete -f $BATS_TESTS_DIR/nginx-deployment-synck8s.yaml
   assert_success
+
+  run kubectl delete -f $BATS_TESTS_DIR/vault_synck8s_v1alpha1_secretproviderclass.yaml
+  assert_success
+
   sleep 20
   result=$(kubectl get secret | grep foosecret | wc -l)
   [[ "$result" == "0" ]]
```
Comment (ritazh) [inline test/bats/vault.bats:198]: As discussed, lets use `-eq` for numeric and `==` for string.

File: cmd/secrets-store-csi-driver/main.go (hunk 2 above)
Comment (aramase) [reply cmd/secrets-store-csi-driver/main.go:101]: Adding the links here for future ref 

https://github.com/kubernetes-sigs/controller-runtime/blob/cea989b02ed02254d751ad30471c40bacd5888fc/pkg/client/client_cache.go#L88-L96
    
newResource always creates a new client - https://github.com/kubernetes-sigs/controller-runtime/blob/cea989b02ed02254d751ad30471c40bacd5888fc/pkg/client/client_cache.go#L51-L68

**Comment by aramase** [comment]
/hold

(for windows tests to pass)
